CREATE OR REPLACE DIRECTORY IMG AS 'C:\sql_files\img\';
GRANT READ, WRITE ON DIRECTORY IMG TO HR;
COMMIT;

SET SERVEROUTPUT ON;




/* Almacenar archivo  en base de datos oracle */

CREATE TABLE IMAGENES(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(150) NOT NULL,
ARCHIVO BLOB NOT NULL
);
CREATE SEQUENCE SQ_IMAGENES START WITH 1;

DECLARE 
    V_IMAGEN BLOB;
    V_ARCHIVO BFILE := BFILENAME('IMG','1.JPG');
    MENSAJE VARCHAR2(100);
BEGIN
    INSERT INTO IMAGENES VALUES(SQ_IMAGENES.NEXTVAL, 'DOG.JPG',EMPTY_BLOB() )
                                RETURN ARCHIVO INTO V_IMAGEN;
                                
   DBMS_LOB.FILEOPEN(V_ARCHIVO, DBMS_LOB.LOB_READONLY);
    
    DBMS_LOB.LOADFROMFILE(V_IMAGEN, V_ARCHIVO, DBMS_LOB.GETLENGTH(V_ARCHIVO));
    
    DBMS_LOB.FILECLOSE(V_ARCHIVO);
    COMMIT;
    
EXCEPTION
WHEN OTHERS THEN --Encuentra cualquier error
    MENSAJE := SQLERRM;
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
    DBMS_LOB.FILECLOSE(V_ARCHIVO);
END;
/

SELECT * FROM IMAGENES;
DROP TABLE IMAGENES;
