/* Almacenar archivo  en base de datos oracle */

CREATE TABLE IMAGENES(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(150) NOT NULL,
ARCHIVO BLOB NOT NULL
);
CREATE SEQUENCE SQ_IMAGENES START WITH 1;

DECLARE 
    V_IMAGEN BLOB;
    V_ARCHIVO BFILE := BFILENAME('IMG','1.JPG');
BEGIN
    INSERT INTO IMAGENES VALUES(SQ_IMAGENES.NEXTVAL, 'TIGRE.JPG',EMPTY_BLOB() )
                                RETURN ARCHIVO INTO V_IMAGEN;
                                
    DBMS_LOB.DBMS_LOB.FILEOPEN(V_FILE, DBMS_LOB.LOB_READONLY);
    
    DBMS_LOB.DBMS_LOB.LOADFROMFILE(V_IMAGEN, V_ARCHIVO, DBMS_LOB.DBMS_LOB.GETLENGTH(V_ARCHIVO));
    
    DBMS_LOB.DBMS_LOB.FILECLOSE(V_ARCHIVO);
    COMMIT;
END:
/
