SELECT * FROM JOBS;

CREATE TABLE  ERROR_HR(
    ID_ERROR NUMBER PRIMARY KEY,
    FECHA_ERROR DATE,
    MENSAJE_ERROR VARCHAR2(500),
    TABLA_ERROR VARCHAR2(100)
);



--Encontrar los  tipos de trabajos cin menos gente
SELECT * FROM EMPLOYEES;


SELECT JOBS.JOB_TITLE, COUNT(EMPLOYEES.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS
FROM JOBS 
JOIN EMPLOYEES ON JOBS.job_id = EMPLOYEES.JOB_ID
GROUP BY JOBS.JOB_TITLE
ORDER BY CANTIDAD_EMPLEADOS ASC;


SELECT * FROM TAB;

SET SERVEROUTPUT ON;

DECLARE 
    CURSOR C_EMPLEOS IS SELECT * FROM JOBS;
    CURSOR C_MENOS_EMPLEADOS IS SELECT JOBS.JOB_TITLE, COUNT(EMPLOYEES.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS
                                FROM JOBS 
                                JOIN EMPLOYEES ON JOBS.job_id = EMPLOYEES.JOB_ID
                                GROUP BY JOBS.JOB_TITLE
                                ORDER BY CANTIDAD_EMPLEADOS ASC;
    V_DESCUENTO_GENERAL NUMBER := 0;
    V_DESCUENTO_ESPECIFICO NUMBER:= 0;
    V_DESCUENTO_TOTAL NUMBER := 0;
BEGIN
    FOR EMPLEO IN C_EMPLEOS LOOP
     V_DESCUENTO_TOTAL := 0;
        V_DESCUENTO_GENERAL := ((2/100) * EMPLEO.MIN_SALARY );
        DBMS_OUTPUT.PUT(EMPLEO.JOB_ID||' '||EMPLEO.JOB_TITLE||' '||EMPLEO.MIN_SALARY||' DESCUENTO GENERAL: '||V_DESCUENTO_GENERAL);
        IF EMPLEO.JOB_TITLE = 'President' THEN
            V_DESCUENTO_ESPECIFICO := ( :PRESIDENTE /100)* EMPLEO.MIN_SALARY;
             V_DESCUENTO_TOTAL := V_DESCUENTO_TOTAL + V_DESCUENTO_ESPECIFICO;
            DBMS_OUTPUT.PUT(' ADEMAS: '||V_DESCUENTO_ESPECIFICO);
        END IF;
         IF EMPLEO.JOB_TITLE = 'Administration Vice President' THEN
            V_DESCUENTO_ESPECIFICO := ( :VICE_PRESIDENTE /100)* EMPLEO.MIN_SALARY;
             V_DESCUENTO_TOTAL := V_DESCUENTO_TOTAL + V_DESCUENTO_ESPECIFICO;
            DBMS_OUTPUT.PUT(' ADEMAS: '||V_DESCUENTO_ESPECIFICO);
        END IF;
         IF EMPLEO.JOB_TITLE = 'Finance Manager' THEN
            V_DESCUENTO_ESPECIFICO := ( :FINANCE_MANAGER /100)* EMPLEO.MIN_SALARY;
             V_DESCUENTO_TOTAL := V_DESCUENTO_TOTAL + V_DESCUENTO_ESPECIFICO;
            DBMS_OUTPUT.PUT(' ADEMAS: '||V_DESCUENTO_ESPECIFICO);
        END IF;
         IF EMPLEO.JOB_TITLE = 'Marketing Manager' THEN
            V_DESCUENTO_ESPECIFICO := ( :MARKETING_MANAGER /100)* EMPLEO.MIN_SALARY;
             V_DESCUENTO_TOTAL := V_DESCUENTO_TOTAL + V_DESCUENTO_ESPECIFICO;
            DBMS_OUTPUT.PUT(' ADEMAS: '||V_DESCUENTO_ESPECIFICO);
        END IF;
        V_DESCUENTO_TOTAL := V_DESCUENTO_TOTAL + V_DESCUENTO_GENERAL;
        DBMS_OUTPUT.PUT_LINE(' DESCUENTO TOTAL:'||V_DESCUENTO_TOTAL);
    END LOOP;
END;
/
