SET SERVEROUTPUT ON;

DECLARE
    CURSOR C1(ID_DEP NUMBER)IS SELECT * 
                            FROM EMPLOYEES 
                            WHERE DEPARTMENT_ID = ID_DEP;
    ID_REQ NUMBER;
    RESULTADO EMPLOYEES%ROWTYPE;
BEGIN
    ID_REQ := :ID;
    OPEN C1(ID_REQ);
    LOOP     
       FETCH C1 INTO RESULTADO;
       EXIT WHEN C1%NOTFOUND;
       DBMS_OUTPUT.PUT_LINE(RESULTADO.FIRST_NAME||' '||RESULTADO.LAST_NAME);
       DBMS_OUTPUT.PUT_LINE('===============');
    END LOOP;
    CLOSE C1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON DATOS');
    WHEN CURSOR_ALREADY_OPEN THEN
     DBMS_OUTPUT.PUT_LINE('NO SE PUEDE RECORRER EL CURSOR, YA QUE ESTA ABIERTO');
    WHEN VALUE_ERROR THEN
     DBMS_OUTPUT.PUT_LINE('ERROR POR VALOR ERRONEO');
    WHEN INVALID_NUMBER THEN
     DBMS_OUTPUT.PUT_LINE('HAY UN ERROR DE CONVERSION');
    WHEN OTHERS THEN --TODAS LAS DEMAS, SIEMPRE VA AL FINAL
     DBMS_OUTPUT.PUT_LINE('ERROR DESCONOCIDO');
      CLOSE C1;
END;
/



