CREATE OR REPLACE DIRECTORY HOTEL AS 'C:\sql_files\hotelLujo\';
GRANT READ, WRITE ON DIRECTORY HOTEL TO PRUEBA2;
COMMIT;

SELECT * FROM HABITACION;
SELECT * FROM TAB;
SELECT * FROM RESERVA;

SELECT HABITACION.ID_HABITACION, COUNT(RESERVA.ID_HABITACION) FROM HABITACION 
JOIN RESERVA ON HABITACION.ID_HABITACION = RESERVA.ID_HABITACION
GROUP BY HABITACION.ID_HABITACION
ORDER BY HABITACION.ID_HABITACION ASC;


CREATE TABLE ERRORES(
ID_ERROR NUMBER PRIMARY KEY,
FECHA_ERROR DATE,
MENSAJE_ERROR VARCHAR2(500)
);

CREATE SEQUENCE SQ_ERRORES
  START WITH 1 INCREMENT BY 1;

ALTER TABLE HABITACION ADD IMAGEN_HABITACION BLOB;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_HABITACIONES IS SELECT * FROM HABITACION;
    V_HABITACION_SIMPLE NUMBER := 2;
    V_HABITACION_DOBLE NUMBER := 4;
    V_HABITACION_COMUNICACION NUMBER := 6;
    V_HABITACION_T_ESTUDIO NUMBER := 8;
    V_HABITACION_SUITE NUMBER := 10;
    V_HABITACION_PRESIDENCIAL NUMBER := 12; 
    V_MENSAJE_ERROR VARCHAR2(500);
    V_ID_HABITACION NUMBER(3) := 0;
    V_IMAGEN BLOB;
    V_ARCHIVO BFILE;
    V_VALOR_ACTUALIZADO NUMBER;
BEGIN
    
    --Toma de valores por pantalla para posible cambio en reglas de negocio
    V_HABITACION_SIMPLE  := :simple;
    V_HABITACION_DOBLE  := :doble;
    V_HABITACION_COMUNICACION  := :comunicacion;
    V_HABITACION_T_ESTUDIO  := :tipo_estudio;
    V_HABITACION_SUITE  := :suite;
    V_HABITACION_PRESIDENCIAL  := :presidencial;
    
    
    FOR FHABITACION IN C_HABITACIONES LOOP
        V_ID_HABITACION := FHABITACION.ID_HABITACION;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'C') THEN
            V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_COMUNICACION/100));
            DBMS_OUTPUT.PUT('ES COMUNICACION '||V_VALOR_ACTUALIZADO||' ');
            V_ARCHIVO := BFILENAME('HOTEL','C.JPG');
                     
        END IF;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'D') THEN
            V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_DOBLE/100));
            DBMS_OUTPUT.PUT('ES DOBLE '||V_VALOR_ACTUALIZADO||' ');
             V_ARCHIVO := BFILENAME('HOTEL','D.JPG');
        END IF;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'S') THEN
             V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_SIMPLE/100));
             DBMS_OUTPUT.PUT('ES SIMPLE '||V_VALOR_ACTUALIZADO||' ');
             V_ARCHIVO := BFILENAME('HOTEL','S.JPG');
        END IF;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'SE') THEN
             V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_SUITE/100));
             DBMS_OUTPUT.PUT('ES SUITE '||V_VALOR_ACTUALIZADO||' ');
             V_ARCHIVO := BFILENAME('HOTEL','SE.JPG');
        END IF;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'SP') THEN
            V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_PRESIDENCIAL/100));
            DBMS_OUTPUT.PUT('ES PRESIDENCIAL '||V_VALOR_ACTUALIZADO||' ');

            V_ARCHIVO := BFILENAME('HOTEL','SP.JPG');
        END IF;
        
        IF(UPPER(FHABITACION.TIPO_HABITACION) = 'T') THEN
            V_VALOR_ACTUALIZADO :=FHABITACION.VALOR_HABITACION + (FHABITACION.VALOR_HABITACION * ( V_HABITACION_T_ESTUDIO/100));
             DBMS_OUTPUT.PUT('ES TIPO ESTUDIO '||V_VALOR_ACTUALIZADO||' ');
            V_ARCHIVO := BFILENAME('HOTEL','T.JPG');
        END IF;
        
        DBMS_OUTPUT.PUT_LINE(V_ID_HABITACION);
        
        -- Acutalizacion de valores a la tabla habitacion
        UPDATE HABITACION
        SET VALOR_HABITACION =  V_VALOR_ACTUALIZADO
        WHERE ID_HABITACION = V_ID_HABITACION;
        
        -- Ingreso de imagenes a la tabla habitacion
        UPDATE HABITACION 
        SET IMAGEN_HABITACION = EMPTY_BLOB()
        WHERE ID_HABITACION = V_ID_HABITACION
        RETURNING IMAGEN_HABITACION INTO V_IMAGEN;
       
        DBMS_LOB.FILEOPEN(V_ARCHIVO, DBMS_LOB.LOB_READONLY);
        DBMS_LOB.LOADFROMFILE(V_IMAGEN, V_ARCHIVO, DBMS_LOB.GETLENGTH(V_ARCHIVO));
        DBMS_LOB.FILECLOSE(V_ARCHIVO);
        COMMIT;
        
    END LOOP;
EXCEPTION
  
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontraron datos'); 
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error por valor erroneo');    
    WHEN INVALID_CURSOR THEN
        DBMS_OUTPUT.PUT_LINE('Se intento una operacion no valida en cursores');
    WHEN INVALID_NUMBER THEN
        DBMS_OUTPUT.PUT_LINE('Se produjo un error en la conversion de datos');
    WHEN CURSOR_ALREADY_OPEN THEN
        DBMS_OUTPUT.PUT_LINE('Se intento abrir un cursor ya abierto');
        CLOSE C_HABITACIONES;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Se ha producido un error');
        V_MENSAJE_ERROR := SQLERRM;
        DBMS_OUTPUT.PUT_LINE(V_MENSAJE_ERROR);        
END;
/
SELECT * FROM HABITACION;
